sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tF1JqPAtWeDziXDVsGc
    access-key-secret: ydpeO2ADtAaY7C52qDDZaawxGqHbZa
    bucket-name: suny1798
